# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'calcoun' do
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

end
