# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'calcoun' do
  pod 'Firebase/Core', :modular_headers => true
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
